export default {
  name: 'Articles',
  updateArticle: 'Edit article',
  nameField: 'Name',
  text: 'Text',
  textCurrent: 'Current text',
  category: 'Category',
  pending: 'Pending',
  ready: 'Ready',
  processing: 'Processing',
  failed: 'Failed',
  disabled: 'Disabled',
  applied: 'Applied',
  ownId: 'Own ID',
  apply: 'Apply',
  rewrite: 'Rewrite',
  disable: 'Disabled',
  askApplyRecord: 'Are you sure that you want to apply this text?',
  askDisableRecord: 'Are you sure that you want to disable this text?',
  updateAndApply: 'Update and Apply',
  successUpdateAndApplyText: 'The record was successfully updated and applied.',
  rewriteArticle: 'Request to rewrite article',
  successRewriteText: 'The request to rewrite the text has been sent.',
  request: 'Request',
  requestExplanation: '',
  write: 'Write',
  writeArticle: 'Request to write text',
  successWriteText: 'Request has been sent.',
  result: 'Result',
};
