export default {
  name: 'Статьи',
  updateArticle: 'Редактировать статью',
  nameField: 'Название',
  text: 'Написанный текст',
  textCurrent: 'Текущий текст',
  category: 'Категория',
  pending: 'В ожидании',
  ready: 'Готово',
  processing: 'Идет написание текста',
  failed: 'Неуспешно',
  disabled: 'Отклонен',
  applied: 'Принят',
  ownId: 'ID сущности',
  apply: 'Принять',
  rewrite: 'Переписать',
  disable: 'Отклонить',
  askApplyRecord: 'Вы точно хотите принять этот текст?',
  askDisableRecord: 'Вы точно хотите отклонить этот текст?',
  updateAndApply: 'Обновить и принять',
  successUpdateAndApplyText: 'Данные были удачно обновлены и приняты.',
};
