export default {
  name: 'Analyzers',
  nameField: 'Name',
  text: 'Text',
  category: 'Category',
  pending: 'Pending',
  ready: 'Ready',
  processing: 'Processing',
  failed: 'Failed',
  ownId: 'Own ID',
  analyze: 'Analyze',
  successAnalyzeText: 'The request to analyze the text has been sent.',
  reanalyze: 'Reanalyze',
  unique: 'unique',
  water: 'Water',
  spam: 'Spam',
  analyzing: 'The request to analyze the text is being proceeding.',
  askReanalyze: 'Do you want to reanalyze the text?',
  skipped: 'Skipped',
  statusEntity: 'Status Entity',
};
