export default {
  name: 'Collection',
  addCollection: 'Add collection',
  updateCollection: 'Edit collection',
  nameField: 'Name',
  publishedAt: 'Published At',
  link: 'Link',
  anons: 'Anons',
  title: 'Title',
  description: 'Description',
  keywords: 'Keywords',
  article: 'Article',
  createCollection: 'Create collection',
  direction: 'Direction',
  text: 'Text',
  additional: 'Additional',
  filters: 'Filters',
  amount: 'Amount',
  schools: 'Schools',
  categories: 'Categories',
  professions: 'Professions',
  teachers: 'Teachers',
  skills: 'Skills',
  tools: 'Tools',
  levels: 'Levels',
  format: 'Format',
  online: 'Online',
  offline: 'Offline',
  rating: 'Rating',
  'rating-4-5': '4.5 and higher',
  'rating-4': '4 and higher',
  'rating-3-5': '3.5 and higher',
  'rating-3': '3 and higher',
  credit: 'Credit',
  free: 'Only free',
  price: 'Price',
  duration: 'Duration',
  sort: 'Sort',
  sortAlphabetic: 'By name',
  sortDate: 'By date',
  sortRating: 'By rating',
  sortPriceAsc: 'By price ascending',
  sortPriceDesc: 'By price descending',
  month0: 'month',
  month1: 'month',
  month2: 'months',
  month3: 'months',
  copied: 'Copied',
};
