export default {
  name: 'Collection',
  addCollection: 'Add collection',
  updateCollection: 'Edit collection',
  nameField: 'Name',
  publishedAt: 'Published At',
  link: 'Link',
  anons: 'Anons',
  title: 'Title',
  description: 'Description',
  keywords: 'Keywords',
  article: 'Article',
  createCollection: 'Create collection',
  direction: 'Direction',
  text: 'Text',
  additional: 'Additional',
  filters: 'Filters',
  amount: 'Amount',
  schools: 'Schools',
};
