export default {
  name: 'Коллекции',
  addCollection: 'Добавить коллекцию',
  updateCollection: 'Редактировать коллекцию',
  nameField: 'Название',
  publishedAt: 'Дата публикации',
  link: 'Ссылка',
  anons: 'Анонс',
  title: 'Тайтл',
  description: 'Описание',
  keywords: 'Ключевые слова',
  article: 'Статья',
  createCollection: 'Создать коллекцию',
  direction: 'Направление',
  text: 'Текст',
  additional: 'Дополнительное описание',
  filters: 'Фильтры',
  amount: 'Количество',
  schools: 'Школы',
  categories: 'Категории',
  professions: 'Профессии',
  teachers: 'Учителя',
  skills: 'Навыки',
  tools: 'Инструменты',
  levels: 'Уровни',
  format: 'Форма обучения',
  online: 'Онлайн',
  offline: 'Оффлайн',
  rating: 'Рейтинг',
  'rating-4-5': '4.5 и выше',
  'rating-4': '4 и выше',
  'rating-3-5': '3.5 и выше',
  'rating-3': '3 и выше',
  credit: 'Рассрочка',
  free: 'Только бесплатные',
  price: 'Цена',
  duration: 'Длительность',
  sort: 'Сортировка',
  sortAlphabetic: 'По алфавиту',
  sortDate: 'По дате',
  sortRating: 'По рейтингу',
  sortPriceAsc: 'Цена: по возрастанию',
  sortPriceDesc: 'Цена: по убыванию',
  month0: 'месяцев',
  month1: 'месяц',
  month2: 'месяца',
  month3: 'месяцев',
};
