export default {
  name: 'Коллекции',
  addCollection: 'Добавить коллекцию',
  updateCollection: 'Редактировать коллекцию',
  nameField: 'Название',
  publishedAt: 'Дата публикации',
  link: 'Ссылка',
  anons: 'Анонс',
  title: 'Тайтл',
  description: 'Описание',
  keywords: 'Ключевые слова',
  article: 'Статья',
  createCollection: 'Создать коллекцию',
  direction: 'Направление',
  text: 'Текст',
  additional: 'Дополнительное описание',
  filters: 'Фильтры',
  amount: 'Количество',
  schools: 'Школы',
};
