export default {
  name: 'Коллекции',
  addCollection: 'Добавить коллекцию',
  updateCollection: 'Редактировать коллекцию',
  header: 'Заголовок',
  publishedAt: 'Дата публикации',
  link: 'Ссылка',
  anons: 'Анонс',
  title: 'Тайтл',
  description: 'Описание',
  keywords: 'Ключевые слова',
  article: 'Статья',
  createCollection: 'Создать коллекцию',
  direction: 'Направление',
};
