version: "3.7"

services:
    app:
        build:
            context: ./
            dockerfile: ./docker/app/Dockerfile
        image: admin-courselandia-ru-app
        container_name: admin-courselandia-ru-app
        restart: unless-stopped
        working_dir: /var/www
        ports:
            - "18000:19000"
        networks:
            - network
        depends_on:
            - php
            - nginx

    php:
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
        image: admin-courselandia-ru-php
        container_name: admin-courselandia-ru-php
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./php:/var/www/php
        networks:
            - network

    nginx:
        image: nginx:alpine
        container_name: admin-courselandia-ru-nginx
        restart: unless-stopped
        ports:
            - ${DOCKER_NGINX_PORT}:17000
        volumes:
            - ./:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - network
networks:
    network:
        driver: bridge
