export default {
  name: 'Promocodes',
  addFaq: 'Add promocode',
  updateFaq: 'Edit promocode',
  createFaq: 'Create promocode',
  schools: 'School',
  title: 'Title',
  description: 'Description',
  minPrice: 'Min price',
  discount: 'Discount',
  discountType: 'Discount type',
  dateStart: 'Date start',
  dateEnd: 'Date end',
  type: 'Type',
  url: 'URL',
  status: 'Status',
  code: 'Code',
  date: 'Date',
  present: 'Present',
  rub: 'RUB',
  applicable: 'Applicable',
};
