export default {
  name: 'Промокоды',
  addPromocode: 'Добавить промокод',
  updatePromocode: 'Редактировать промокод',
  createPromocode: 'Создать промокод',
  school: 'Школа',
  title: 'Название',
  description: 'Описание',
  minPrice: 'Минимальная цена',
  discount: 'Скидка',
  discountType: 'Тип скидки',
  dateStart: 'Дата начала',
  dateEnd: 'Дата окончания',
  type: 'Тип промокода',
  url: 'URL',
  status: 'Статус',
  code: 'Код',
  date: 'Дата',
  present: 'Подарок',
  rub: 'Рубли',
  applicable: 'Действует',
  percent: 'Проценты',
};
