export default {
  name: 'Промокоды',
  addFaq: 'Добавить промокод',
  updateFaq: 'Редактировать промокод',
  createFaq: 'Создать промокод',
  school: 'Школа',
  title: 'Название',
  description: 'Описание',
  minPrice: 'Минимальная цена',
  discount: 'Скидка',
  discountType: 'Тип скидки',
  dateStart: 'Дата начала',
  dateEnd: 'Дата окончания',
  type: 'Тип промоода',
  url: 'URL',
  status: 'Статус',
  code: 'Код',
  date: 'Дата',
  present: 'Подарок',
  rub: 'Рубли',
  applicable: 'Действует',
};
