export default {
  adminSystem: 'Admin system',
  page404: '404 — Page not found!',
  description404: 'Sorry, the page you visited does not exist.',
  rememberMe: 'Remember Me',
  dashboard: 'Dashboard',
  login: 'Login',
  password: 'Password',
  success: 'Success',
  successCreateText: 'The record was successfully created.',
  successUpdateText: 'The record was successfully updated.',
  enter: 'Submit',
  reset: 'Reset',
  close: 'Close',
  loginForm: 'Login Form',
  closeAlert: 'Close alert',
  actions: 'Actions',
  notifications: 'Notifications',
  viewAllNotification: 'Vew all notifications',
  home: 'Dashboard',
  cleanCache: 'Clean cache',
  cleanedCache: 'The cache was cleaned successfully.',
  alerts: 'Alerts',
  configs: 'Configs',
  logout: 'Logout',
  agree: 'Agree',
  disagree: 'Disagree',
  confirmLogout: 'Do you really want to logout?',
  confirmChangeStatus: 'Do you really want to change the status of this record?',
  profile: 'Profile',
  destroyImage: 'Destroy image',
  image: 'Image',
  confirmDestroyImage: 'Do you really want to destroy the image?',
  caution: 'Caution',
  update: 'Update',
  successDestroyImage: 'The image has been destroyd successfully.',
  search: 'Search',
  upload: 'Upload',
  add: 'Add',
  destroy: 'Destroy',
  up: 'Up',
  down: 'Down',
  edit: 'Edit',
  alert: 'Alert',
  ok: 'OK',
  askDestroyRecord: 'Do you really want to destroy the record?',
  askDetachRecord: 'Do you really want to detach the record?',
  askDestroyRecords: 'Do you really want to destroy the records?',
  nodePositionChanged: 'The position of node has been changed.',
  create: 'Create',
  yes: 'Yes',
  no: 'No',
  status: 'Status',
  active: 'Active',
  deactivated: 'Deactivated',
  disabled: 'Disabled',
  id: 'ID',
  label: 'Label',
  name: 'Name',
  index: 'Index',
  weight: 'Weight',
  date: 'Date',
  time: 'Time',
  dateFrom: 'Date from',
  dateTo: 'Date to',
  from: 'From',
  to: 'To',
  title: 'Title',
  description: 'Description',
  content: 'Content',
  email: 'Email',
  phone: 'Phone',
  fio: 'Name',
  showBy: 'Show By',
  error: 'Error',
  file: 'File',
  value: 'Value',
  url: 'URL',
  type: 'Type',
  icon: 'Icon',
  default: 'Default',
  updateStatus: 'The status has been changed successfully.',
  askStatusRecord: 'Do you really want to change the status the record?',
  parameterSaved: 'The parameter has been saved.',
  link: 'Link',
  header: 'Header',
  user: 'User',
  info: 'Info',
  price: 'Price',
  remove: 'Remove',
  free: 'Free',
  backHome: 'Back Home',
  admin: 'Admin',
  manager: 'Manager',
  meta: 'Metadata',
  go: 'Go',
  review: 'Review',
  draft: 'Draft',
  warning: 'Warning',
  notEmpty: 'The value cannot be empty.',
  detach: 'Detach',
};
