export default {
  adminSystem: 'Административная система',
  page404: '404 — Страница не найдена',
  description404: 'Извините, но страницу, которую вы запрашиваете не существует!',
  rememberMe: 'Запомнить меня',
  dashboard: 'Панель управления',
  login: 'Логин',
  password: 'Пароль',
  success: 'Удачно',
  successCreateText: 'Данные были удачно добавлены.',
  successUpdateText: 'Данные были удачно обновлены.',
  enter: 'Войти',
  reset: 'Сбросить',
  close: 'Закрыть',
  loginForm: 'Вход в систему',
  closeAlert: 'Закрыть окно предупреждения',
  actions: 'Действия',
  notifications: 'Предупреждения',
  viewAllNotification: 'Посмотреть все предупреждения',
  home: 'Панель управления',
  cleanCache: 'Удалить кеш',
  cleanedCache: 'Кеш был успешно удален.',
  alerts: 'Предупреждения',
  configs: 'Конфигурации',
  logout: 'Выход',
  agree: 'Подтвердить',
  disagree: 'Отказаться',
  confirmLogout: 'Вы действительно хотите выйти из системы?',
  confirmChangeStatus: 'Вы действительно хотите изменить статус этой записи?',
  profile: 'Профайл',
  destroyImage: 'Удалить изображение',
  image: 'Изображение',
  confirmDestroyImage: 'Вы действительно хотите удалить изображение?',
  caution: 'Внимание',
  update: 'Обновить',
  successDestroyImage: 'Изображение было удачно удалено.',
  search: 'Поиск',
  upload: 'Загрузить',
  add: 'Добавить',
  destroy: 'Удалить',
  up: 'Вверх',
  down: 'Вниз',
  edit: 'Редактировать',
  alert: 'Внимание',
  ok: 'OK',
  askDestroyRecord: 'Вы точно хотите удалить эту запись?',
  askDestroyRecords: 'Вы точно хотите удалить эти записи?',
  nodePositionChanged: 'Позиции записи была изменена.',
  create: 'Создать',
  yes: 'Да',
  no: 'Нет',
  status: 'Статус',
  active: 'Активен',
  deactivated: 'Неактивен',
  disabled: 'Отключено',
  id: 'ID',
  label: 'Метка',
  name: 'Название',
  index: 'Индекс',
  weight: 'Вес',
  date: 'Дата',
  time: 'Время',
  dateFrom: 'Начальная дата',
  dateTo: 'Дата окончания',
  title: 'Заголовок',
  description: 'Описание',
  content: 'Контент',
  email: 'Почта',
  phone: 'Телефон',
  fio: 'Имя',
  showBy: 'Показывать по',
  error: 'Ошибка',
  file: 'Файл',
  value: 'Значение',
  url: 'URL',
  type: 'Тип',
  icon: 'Иконка',
  default: 'По умолчанию',
  updateStatus: 'Статус был успешно изменен.',
  askStatusRecord: 'Вы действительно хотите изменить статус этой записи?',
  parameterSaved: 'Параметр был сохранен.',
  link: 'Ссылка',
  header: 'Заголовок',
  user: 'Пользователь',
  info: 'Информация',
  price: 'Цена',
  remove: 'Убрать',
  free: 'Бесплатно',
  backHome: 'Вернуться домой',
  admin: 'Администратор',
  manager: 'Менеджер',
  meta: 'Мета данные',
  go: 'Перейти',
  review: 'В рассмотрении',
};
