export default {
  name: 'Sections',
  addSection: 'Add section',
  updateSection: 'Edit section',
  createSection: 'Create section',
  nameField: 'Name',
  header: 'Header',
  link: 'Link',
  text: 'Text',
  additional: 'Additional',
  title: 'Title',
  description: 'Description',
  keywords: 'Keywords',
  level: 'Level',
  free: 'Free',
  type: 'Type',
  nameType: 'Type name',
  category: 'Category',
  direction: 'Direction',
  profession: 'Profession',
  school: 'School',
  skill: 'Skill',
  teacher: 'Teacher',
  tool: 'Tool',
};
