export default {
  name: 'Разделы',
  addSection: 'Добавить раздел',
  updateSection: 'Редактировать раздел',
  createSection: 'Создать раздел',
  nameField: 'Название',
  header: 'Заголовок',
  text: 'Текст',
  additional: 'Дополнительное описание',
  title: 'Тайтл',
  description: 'Описание',
  keywords: 'Ключевые слова',
  level: 'Уровень',
  free: 'Бесплатный',
  type: 'Тип раздела',
  nameType: 'Название раздела',
  category: 'Категория',
  direction: 'Направления',
  profession: 'Профессия',
  school: 'Школа',
  skill: 'Навык',
  teacher: 'Учитель',
  tool: 'Инструмент',
  url: 'URL',
};
