export default {
  name: 'Categories',
  addCategory: 'Add category',
  updateCategory: 'Edit category',
  createCategory: 'Create category',
  nameField: 'Name',
  header: 'Header',
  link: 'Link',
  text: 'Text',
  additional: 'Additional',
  title: 'Title',
  description: 'Description',
  keywords: 'Keywords',
  directions: 'Directions',
  professions: 'Professions',
};
