export default {
  name: 'Категории',
  addCategory: 'Добавить категорию',
  updateCategory: 'Редактировать категорию',
  createCategory: 'Создать категорию',
  nameField: 'Название',
  header: 'Заголовок',
  link: 'Ссылка',
  text: 'Текст',
  additional: 'Дополнительное описание',
  title: 'Тайтл',
  description: 'Описание',
  keywords: 'Ключевые слова',
  directions: 'Направления',
  professions: 'Профессии',
};
