export default {
  name: 'Teachers',
  addTeacher: 'Add teacher',
  updateTeacher: 'Edit teacher',
  nameField: 'Name',
  link: 'Link',
  text: 'Text',
  rating: 'Rating',
  title: 'Title',
  description: 'Description',
  keywords: 'Keywords',
  image: 'Image',
  createTeacher: 'Create Teacher',
  directions: 'Directions',
  schools: 'Schools',
  city: 'City',
  copied: 'Copied',
  comment: 'Comment',
  experiences: 'Experiences',
  place: 'Place',
  position: 'Position',
  started: 'Started',
  finished: 'Finished',
  weight: 'Weight',
  socialMedias: 'Social Medias',
  value: 'Value',
  nameSocialMedia: 'Social Media',
};
