export default {
  name: 'Teachers',
  addTeacher: 'Add teacher',
  updateTeacher: 'Edit teacher',
  nameField: 'Name',
  link: 'Link',
  text: 'Text',
  additional: 'Additional',
  rating: 'Rating',
  title: 'Title',
  description: 'Description',
  keywords: 'Keywords',
  image: 'Image',
  createTeacher: 'Create Teacher',
  directions: 'Directions',
  schools: 'Schools',
  city: 'City',
  copied: 'Copied',
  comment: 'Comment',
  experiences: 'Experiences',
  place: 'Place',
  position: 'Position',
  started: 'Started',
  finished: 'Finished',
  weight: 'Weight',
  socialMedias: 'Social Medias',
  value: 'Value',
  nameSocialMedia: 'Social Media',
  linkedIn: 'LinkedIn',
  facebook: 'Facebook',
  vk: 'VK',
  ok: 'OK',
  telegram: 'Telegram',
  whatsApp: 'WhatsApp',
  behance: 'Behance',
  dribble: 'Dribble',
  instagram: 'Instagram',
  twitter: 'Twitter',
  discord: 'Discord',
  youTube: 'YouTube',
  twitch: 'Twitch',
  tikTok: 'TikTok',
  site: 'Web-site',
  vc: 'VC',
  yandex_q: 'Yandex Q',
  github: 'Github',
  gitlab: 'Gitlab',
  skype: 'Skype',
  youdo: 'Youdo',
  pinterest: 'Pinterest',
  yandex_dzen: 'Yandex dzen',
  habr_career: 'Habr Career',
};
