export default {
  name: 'Учителя',
  addTeacher: 'Добавить учителя',
  updateTeacher: 'Редактировать школу',
  nameField: 'Название',
  link: 'Ссылка',
  text: 'Текст',
  rating: 'Рейтинг',
  title: 'Тайтл',
  description: 'Описание',
  keywords: 'Ключевые слова',
  image: 'Изображение',
  createTeacher: 'Создать учителя',
  directions: 'Направления',
  schools: 'Школы',
};
