export default {
  name: 'Учителя',
  addTeacher: 'Добавить учителя',
  updateTeacher: 'Редактировать учителя',
  nameField: 'ФИО',
  link: 'Ссылка',
  text: 'Текст',
  rating: 'Рейтинг',
  title: 'Тайтл',
  description: 'Описание',
  keywords: 'Ключевые слова',
  image: 'Изображение',
  createTeacher: 'Создать учителя',
  directions: 'Направления',
  schools: 'Школы',
  city: 'Город',
  copied: 'Биография скопирована',
  comment: 'Комментарий',
};
