export default {
  name: 'Учителя',
  addTeacher: 'Добавить учителя',
  updateTeacher: 'Редактировать учителя',
  nameField: 'ФИО',
  link: 'Ссылка',
  text: 'Текст',
  additional: 'Дополнительное описание',
  rating: 'Рейтинг',
  title: 'Тайтл',
  description: 'Описание',
  keywords: 'Ключевые слова',
  image: 'Изображение',
  createTeacher: 'Создать учителя',
  directions: 'Направления',
  schools: 'Школы',
  city: 'Город',
  copied: 'Биография скопирована',
  comment: 'Комментарий',
  experiences: 'Опыт работы',
  place: 'Место',
  position: 'Должность',
  started: 'Начала работы',
  finished: 'Окончание работы',
  weight: 'Вес',
  socialMedias: 'Социальные сети',
  value: 'Значение',
  nameSocialMedia: 'Социальная сеть',
  linkedIn: 'LinkedIn',
  facebook: 'Facebook',
  vk: 'VK',
  ok: 'OK',
  telegram: 'Telegram',
  whatsApp: 'WhatsApp',
  behance: 'Behance',
  dribble: 'Dribble',
  instagram: 'Instagram',
  twitter: 'Twitter',
  discord: 'Discord',
  youTube: 'YouTube',
  twitch: 'Twitch',
  tikTok: 'TikTok',
  site: 'Сайт',
  vc: 'VC',
  yandex_q: 'Yandex Q',
  github: 'Github',
  gitlab: 'Gitlab',
  skype: 'Skype',
  youdo: 'Youdo',
  pinterest: 'Pinterest',
  yandex_dzen: 'Яндекс.Дзен',
  habr_career: 'Хабр Карьера',
};
