export default {
  name: 'Reviews',
  addReview: 'Add review',
  updateReview: 'Edit review',
  createReview: 'Create review',
  schools: 'School',
  nameAuthor: 'Name',
  title: 'Title',
  advantages: 'Advantages',
  disadvantages: 'Disadvantages',
  rating: 'Rating',
  status: 'Status',
  createdAt: 'Created At',
  course: 'Course',
};
