export default {
  name: 'Отзывы',
  addReview: 'Добавить отзыв',
  updateReview: 'Редактировать отзыв',
  createReview: 'Создать отзыв',
  school: 'Школа',
  nameAuthor: 'Автор',
  title: 'Заголовок',
  text: 'Текст',
  advantages: 'Достоинства',
  disadvantages: 'Недостатки',
  rating: 'Рейтинг',
  status: 'Статус',
  createdAt: 'Создан',
  course: 'Курс',
};
