import ECurrency from '@/enums/modules/course/currency';
import EDuration from '@/enums/modules/course/duration';
import ELanguage from '@/enums/modules/course/language';
import EStatus from '@/enums/modules/course/status';
import ICategory from '@/interfaces/modules/category/category';
import IEmployment from '@/interfaces/modules/course/employment';
import IFeature from '@/interfaces/modules/course/feature';
import ILearn from '@/interfaces/modules/course/learn';
import ILevel from '@/interfaces/modules/course/level';
import IDirection from '@/interfaces/modules/direction/direction';
import IImage from '@/interfaces/modules/image';
import IMetatag from '@/interfaces/modules/metatag';
import IProfession from '@/interfaces/modules/profession/profession';
import ISchool from '@/interfaces/modules/school/school';
import ISkill from '@/interfaces/modules/skill/skill';
import ITeacher from '@/interfaces/modules/teacher/teacher';
import ITool from '@/interfaces/modules/tool/tool';
import IColumn from '@/interfaces/molecules/table/column';
import TId from '@/types/id';

export default interface IPublication extends IColumn {
  id: TId;
  uuid: string;
  metatag_id: TId;
  school_id: TId;
  image_big_id: IImage | null;
  image_middle_id: IImage | null;
  image_small_id: IImage | null;
  header: string;
  text: string | null;
  header_morphy: string;
  text_morphy: string | null;
  link: string;
  url: string;
  language: ELanguage | null;
  rating: number | null;
  price: number | null;
  price_discount: number | null;
  price_recurrent_price: number | null;
  currency: ECurrency | null;
  online: boolean | null;
  employment: boolean | null;
  duration: number | null;
  duration_rate: number | null;
  duration_unit: EDuration | null;
  lessons_amount: number | null;
  modules_amount: number | null;
  status: EStatus;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;

  metatag: IMetatag;
  school: Array<ISchool> | null;
  directions: Array<IDirection> | null;
  professions: Array<IProfession> | null;
  categories: Array<ICategory> | null;
  skills: Array<ISkill> | null;
  teachers: Array<ITeacher> | null;
  tools: Array<ITool> | null;
  levels: Array<ILevel> | null;
  learns: Array<ILearn> | null;
  employments: Array<IEmployment> | null;
  features: Array<IFeature> | null;
}
