export default {
  name: 'Courses',
  addCourse: 'Add course',
  updateCourse: 'Edit course',
  header: 'Header',
  school: 'School',
  price: 'Price',
  directions: 'Directions',
  professions: 'Professions',
  createCourse: 'Create Course',
  link: 'Link',
  categories: 'Categories',
  skills: 'Skills',
  tools: 'Tools',
  levels: 'Levels',
  url: 'URL',
  rating: 'Rating',
  priceDiscount: 'Price Discount',
  priceRecurrentPrice: 'Price Recurrent Price',
  currency: 'Currency',
  online: 'Online',
  employment: 'Employment',
  duration: 'Duration',
  durationUnit: 'Duration Unit',
  day: 'Day',
  week: 'Week',
  month: 'Month',
  year: 'Year',
  lessonsAmount: 'Lessons amount',
  modulesAmount: 'Modules amount',
  title: 'Title',
  description: 'Description',
  keywords: 'Keywords',
  text: 'Text',
  ru: 'Russia',
  en: 'English',
  language: 'Language',
  rub: '₽',
  usd: '$',
  eur: '€',
  addition: 'Addition',
  teachers: 'Teachers',
  learns: 'Learns',
  employments: 'Employments',
  features: 'Features',
  video: 'Video',
  certificate: 'Certificate',
  checkbox: 'Checkbox',
  calendar: 'Calendar',
  note: 'Note',
};
