export default {
  name: 'Курсы',
  addCourse: 'Добавить курс',
  updateCourse: 'Редактировать курс',
  nameCourse: 'Название',
  header: 'Заголовок',
  school: 'Школа',
  price: 'Цена',
  directions: 'Направления',
  professions: 'Профессии',
  createCourse: 'Создать курс',
  link: 'Ссылка',
  categories: 'Категории',
  skills: 'Навыки',
  tools: 'Инструменты',
  levels: 'Уровни',
  url: 'URL',
  rating: 'Рейтинг',
  priceOld: 'Старая цена',
  priceRecurrentPrice: 'Цена по кредиту',
  currency: 'Валюта',
  online: 'Онлайн',
  employment: 'Помощь трудоустройства',
  duration: 'Продолжительность',
  durationUnit: 'Единица измерения',
  day: 'День',
  week: 'Неделя',
  month: 'Месяц',
  year: 'Год',
  lessonsAmount: 'Количество уроков',
  modulesAmount: 'Количество модулей',
  title: 'Тайтл',
  description: 'Описание',
  keywords: 'Ключевые слова',
  text: 'Текст',
  ru: 'Русский',
  en: 'Английский',
  language: 'Язык',
  rub: '₽',
  usd: '$',
  eur: '€',
  addition: 'Дополнительно',
  teachers: 'Учителя',
  learns: 'Чему научитесь',
  employments: 'Трудоустройства',
  processes: 'Процесс обучения',
  features: 'Особенности',
  video: 'Видео',
  certificate: 'Сертификат',
  checkbox: 'Чекбокс',
  calendar: 'Календарь',
  note: 'Заметка',
};
