export default {
  name: 'Directions',
  addDirection: 'Add direction',
  updateDirection: 'Edit direction',
  createDirection: 'Create direction',
  nameField: 'Name',
  header: 'Header',
  link: 'Link',
  text: 'Text',
  title: 'Title',
  description: 'Description',
  keywords: 'Keywords',
  weight: 'Weight',
  additional: 'Additional',
};
