export default {
  name: 'Направления',
  addDirection: 'Добавить направление',
  updateDirection: 'Редактировать направление',
  createDirection: 'Создать направление',
  nameField: 'Название',
  header: 'Заголовок',
  link: 'Ссылка',
  text: 'Текст',
  title: 'Тайтл',
  description: 'Описание',
  keywords: 'Ключевые слова',
  weight: 'Вес',
  additional: 'Дополнительное описание',
};
